from selenium.webdriver.common.by import By

class HomePageLocator:
    scooter_logo = [By.XPATH, '//a[@class="Header_LogoScooter__3lsAR"]']
    yandex_logo = [By.XPATH, '//a[@class="Header_LogoYandex__3TSOI"]']
    upper_order_button = [By.CLASS_NAME,'Button_Button__ra12g']
    lower_order_button = [By.XPATH,'//button[@class="Button_Button__ra12g Button_UltraBig__UU3Lp"]']
    lower_order_button = [By.XPATH,'//button[@class="Button_Button__ra12g Button_Middle__1CSJM"]']
    order_status_button = [By.CLASS_NAME,'Header_Link__1TAG7']
    FAQ_window = [By.CLASS_NAME, 'Home_FAQ__3uVm4']
    FAQ_1 = [By.ID,'accordion__heading-0']
    FAQ_2 = [By.ID,'accordion__heading-1']
    FAQ_3 = [By.ID,'accordion__heading-2']
    FAQ_4 = [By.ID,'accordion__heading-3']
    FAQ_5 = [By.ID,'accordion__heading-4']
    FAQ_6 = [By.ID,'accordion__heading-5']
    FAQ_7 = [By.ID,'accordion__heading-6']
    FAQ_8 = [By.ID,'accordion__heading-7']
    FAQ_1_text = [By.XPATH, '//*[@id="accordion__panel-0"]/p']
    FAQ_2_text = [By.XPATH, '//*[@id="accordion__panel-1"]/p']
    FAQ_3_text = [By.XPATH, '//*[@id="accordion__panel-2"]/p']
    FAQ_4_text = [By.XPATH, '//*[@id="accordion__panel-3"]/p']
    FAQ_5_text = [By.XPATH, '//*[@id="accordion__panel-4"]/p']
    FAQ_6_text = [By.XPATH, '//*[@id="accordion__panel-5"]/p']
    FAQ_7_text = [By.XPATH, '//*[@id="accordion__panel-6"]/p']
    FAQ_8_text = [By.XPATH, '//*[@id="accordion__panel-7"]/p']